spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
app:
  jwt:
    key: ${JWT_KEY}
    accessTokenValidityInMilliseconds: ${JWT_ACCESS_TOKEN_EXPIRATION}
server:
  servlet:
    context-path: /api
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}