spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2

app:
  jwt:
    key: ${JWT_KEY}
    accessTokenValidityInMilliseconds: ${JWT_ACCESS_TOKEN_EXPIRATION}
server:
  servlet:
    context-path: /api
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}